- name: Install AUR libretro cores + wineproton manager for lutris
  yay:
    name: 
      #- libretro-mame2003-plus-git
      #- libretro-easyrpg-player
      - protonup-qt
    state: present
  become: yes

- name: Install libretro MAME core
  package:
    name: libretro-mame
    state: present
  become: yes