- name: Install discord for arch and tw
  package: 
    name: discord
    state: present
  become: yes

# There has been error in some case because of this, keeping it commented
#- name: TW dependency for discord
#  package:
#    name: libatomic1
#    state: present
#  become: yes
#  when: distro=="tw"